spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: transfers-realization-service
  profiles:
    active: production

eureka:
  client: ${eureka-client}

server:
  port: 9991